# Generated by Django 5.1.1 on 2024-11-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
