# Generated by Django 5.1.1 on 2024-11-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_kitap_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
