# Generated by Django 5.1.1 on 2024-11-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_kitap_category_alter_kitap_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
