# Generated by Django 5.1.1 on 2024-11-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitap',
            name='category',
        ),
        migrations.AddField(
            model_name='kitap',
            name='categories',
            field=models.ManyToManyField(to='courses.category'),
        ),
    ]
