# Generated by Django 5.1.1 on 2024-11-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_uploadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitap',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='kitap',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
