# Generated by Django 5.1.1 on 2024-12-05 07:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_kitap_imageurl_kitap_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='subtitle',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
