# Generated by Django 5.1.1 on 2024-12-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_kitap_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='summary',
            field=models.TextField(default='Bu kitabın özeti anlık olarak bulunmamaktadır.'),
        ),
    ]
