# Generated by Django 5.1.1 on 2024-12-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_kitap_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='summary',
            field=models.CharField(max_length=10000, null='Bu kitabın özeti anlık olarak bulunmamaktadır.'),
        ),
    ]
