# Generated by Django 5.1.1 on 2024-12-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_kitap_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='summary',
            field=models.CharField(default='Bu kitabın özeti anlık olarak bulunmamaktadır.', max_length=10000),
        ),
    ]
