# Generated by Django 5.1.1 on 2025-01-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_kitap_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitap',
            name='summary',
            field=models.CharField(max_length=10000),
        ),
    ]
